### PR TITLE
add toggle value for PSS migration

### PR DESCRIPTION
**Pull request by bdehri**
### Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by AndiDog — CHANGES_REQUESTED** [review]
There are missing changes. Please check after `make generate && grep -rE 'Capabilities.APIVersions.Has.*PodSec' .` which files may still need to be touched.

**Comment by fiunchinho** [comment]
Yeah, the contents of the `helm` folder are generated based on what's [in the config folder](https://github.com/giantswarm/cluster-api-provider-aws-app/tree/master/config/helm), using `kustomize`.

**Comment by bdehri** [comment]
> Yeah, the contents of the `helm` folder are generated based on what's [in the config folder](https://github.com/giantswarm/cluster-api-provider-aws-app/tree/master/config/helm), using `kustomize`.

AFAIK, PSPs were just copied over from copy folder.

**Comment by fiunchinho** [comment]
That's a weird way of doing it IMHO, we are mixing two different ways of adding files into the `helm` folder. I would add them as resources to kustomize.

**Comment by bdehri** [comment]
> That's a weird way of doing it IMHO, we are mixing two different ways of adding files into the `helm` folder. I would add them as resources to kustomize.

I will do that.

**Comment by fiunchinho** [comment]
> As I understand, It is not possible to use helm template functions with kustomize (include,if etc.). So, moving the file to config directory and adding it to kustomization yaml does not work.

That's why we don't use template functions on the config folder files. That's how it works for all the other resources/manifests. This one doesn't have to be different.
For the conditional at the beginning of the file `{{- if not .Values.global.podSecurityStandards.enforced }}`, that's where it gets complicated. We have the `hack/wrap-with-conditional.sh` file to add conditionals to other manifests, we could do the same for PSP. But then again, we can improve this later on, we don't need to tackle it now.

**Comment by bdehri** [comment]
I would like to leave it like this for now and close the umbrella issue about PSPs.

**Review by fiunchinho — APPROVED** [review]

**Review by AndiDog — APPROVED** [review]

**Pull request merged**
